* installing validators scripts * support only 64bit architecture for now (can'tt get SpiderMonkey * compile for i386) * run check support for objclint-coordinator * test call to print for JS runtime works!!!

diff --git a/src/objclint-xcodebuild b/src/objclint-xcodebuild
--- a/src/objclint-xcodebuild
+++ b/src/objclint-xcodebuild
@@ -21,7 +21,14 @@ cat > /tmp/ObjclintResourcePlist.plist << EOL
 </plist>
 EOL
 
-/opt/local/bin/objclint-coordinator --drop-session "`pwd`"
+/opt/local/bin/objclint-coordinator&
+sleep 1
+/opt/local/bin/objclint-coordinator --check
+
+if [ $? -gt 0 ]; then
+    echo "Failed to start objclint-coordinator"
+    exit 1
+fi
 
 xcodebuild \
     CC="$OBJCLINT_LOCATION"\
